=== VolkswAIgen/list/volkswaigen.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
					 targetNamespace="https://www.volkswaigen.org/list"
					 xmlns="https://www.volkswaigen.org/list"
					 elementFormDefault="qualified">
	<xs:attribute name="regex" type="xs:string" />
	<xs:simpleType name="entry_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ip-address"/>
			<xs:enumeration value="user-agent"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attribute name="value-type" type="entry_type" />

	<xs:element name="entry">
		<xs:complexType>
			<xs:attribute ref="value-type" use="required"/>
			<xs:attribute ref="regex" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="list">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="entry" minOccurs="1" maxOccurs="unbounded" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== VolkswAIgen/list/list.xml
<?xml version="1.0" encoding="UTF-8" ?>
<list xmlns="https://www.volkswaigen.org/list"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="https://www.volkswaigen.org/list https://www.volkswaigen.org/xml/xsd/volkswaigen.xsd"
>
	<!--
	VolkswAIgen - Adapt your responses when under AI training

  Copyright (C) 2024 VolkswAIgen-Team

  This program is free software: you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version. This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  details.

  You should have received a copy of the GNU General Public License along with
  this program. If not, see <http://www.gnu.org/licenses/>.
  -->
	<entry type="user-agent" value="GPTBot" source="https://platform.openai.com/docs/gptbot"/>
	<entry type="user-agent" value="ChatGPT-User" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="23.98.142.176/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="40.84.180.224/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="13.65.240.240/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="20.97.189.96/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="20.161.75.208/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="52.225.75.208/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="52.156.77.144/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="40.84.180.64/28" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="user-agent" value="https://openai.com/bot" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="52.230.152.0/24" source="https://openai.com/gptbot.json"/>
	<entry type="ip-address" value="52.233.106.0/24" source="https://openai.com/gptbot.json"/>
	<entry type="user-agent" value="OAI-SearchBot" source="https://platform.openai.com/docs/plugins/bot"/>
	<entry type="ip-address" value="20.42.10.176/28" source="https://openai.com/searchbot.json"/>
	<entry type="ip-address" value="172.203.190.128/28" source="https://openai.com/searchbot.json"/>
	<entry type="user-agent" value="Google-Extended" source="https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers?hl=de"/>
	<entry type="user-agent" value="CCBot" source="https://commoncrawl.org/ccbot"/>
	<entry type="user-agent" value="PerplexityBot" source="https://www.cyberciti.biz/web-developer/block-openai-bard-bing-ai-crawler-bots-using-robots-txt-file/"/>
	<entry type="ip-address" value="54.90.207.250/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="ip-address" value="23.22.208.105/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="ip-address" value="54.242.1.13/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="ip-address" value="18.208.251.246/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="ip-address" value="34.230.5.59/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="ip-address" value="18.207.114.171/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="ip-address" value="54.221.7.250/32" source="https://www.perplexity.ai/perplexitybot.json"/>
	<entry type="user-agent" value="anthropic-ai" source="https://www.cyberciti.biz/web-developer/block-openai-bard-bing-ai-crawler-bots-using-robots-txt-file/"/>
	<entry type="user-agent" value="Claude-Web" source="https://www.cyberciti.biz/web-developer/block-openai-bard-bing-ai-crawler-bots-using-robots-txt-file/"/>
	<entry type="user-agent" value="ClaudeBot" source="https://www.cyberciti.biz/web-developer/block-openai-bard-bing-ai-crawler-bots-using-robots-txt-file/"/>
	<entry type="user-agent" value="anthropic-ai" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="Applebot-Extended" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="Bytespider" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="CCBot" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="cohere-ai" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="Diffbot" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="FacebookBot" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="GoogleOther" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="ImagesiftBot" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/" />
	<entry type="user-agent" value="PerplexityBot" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="OmigiliBot" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="Omigili" source="https://www.foundationwebdev.com/2023/11/which-web-crawlers-are-associated-with-ai-crawlers/"/>
	<entry type="user-agent" value="YouBot" source="https://darkvisitors.com/agents"/>
	<entry type="user-agent" value="AppleBot" source="https://darkvisitors.com/agents"/>
	<entry type="user-agent" value="Amazonbot" source="https://darkvisitors.com/agents"/>
	<entry type="user-agent" value="omgili" source="https://darkvisitors.com/agents"/>
	<entry type="user-agent" value="FacebookBot" source="https://darkvisitors.com/agents"/>
	<entry type="user-agent" value="ClaudeBot" source="https://darkvisitors.com/agents"/>
</list>
